system CopyOfNiebla
{
    category                                    MisParticulas
    technique 
    {
        emitted_emitter_quota                   100
        material                                PUMediaPack/Streak_01
        default_particle_width                  50.0138
        default_particle_height                 2.01379
        default_particle_depth                  1.01379
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       70
            angle                               50
            time_to_live                        dyn_random
            {
                min                             3
                max                             8
            }
            velocity                            2.12759
            box_width                           400
            box_height                          7
            box_depth                           1
        }
        affector                                LinearForce Affector0
        {
            force_vector                        7 0 0
            force_application                   average
        }
    }
}
