system FlareLaserBall
{
    category                                    MisParticulas
    technique Technique131
    {
        visual_particle_quota                   90
        material                                PUMediaPack/Flare_01
        default_particle_width                  30
        default_particle_height                 30
        renderer                                Billboard
        {
        }
        emitter                                 Box Emitter140
        {
            angle                               dyn_random
            {
                min                             20
                max                             160
            }
            time_to_live                        2
            velocity                            20
            duration                            5
            direction                           -1 1 0
            orientation                         1 -1 -1 0
            box_width                           2
            box_height                          2
            box_depth                           0.1
        }
        affector                                Colour Affector193
        {
            time_colour                         0    0.54902 1 1 1
            time_colour                         0.328261  0 0.768627 0.768627 1
            time_colour                         0.584783  0 0.360784 0.466667 1
            time_colour                         1    0 0 0 0
        }
    }
}
