system humoSangre
{
    scale                                       8 5 3
    category                                    Explosion
    technique Fire
    {
        visual_particle_quota                   100
        material                                PUMediaPack/Smoke_11
        renderer                                Billboard
        {
        }
        emitter                                 Point FireEmitter
        {
            emission_rate                       35
            angle                               360
            time_to_live                        0.5
            velocity                            44
            duration                            3.5
            all_particle_dimensions             dyn_random
            {
                min                             6
                max                             14
            }
            colour                              0.878431 0.878431 0.878431 1
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -90
                max                             90
            }
            rotation_speed                      0
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 0 1
            time_colour                         0.428261  1 0 0 0.498039
            time_colour                         0.68913  0.501961 0 0 0.2
            time_colour                         1    0.254902 0 0.254902 0
        }
    }
}
