-- author: Cesar Manuel Paz Guzman

entidadesIniciales =
{
	--tipo de entidad y cantidad
	Player = 1,
	Potenciador1 = 3,
	Potenciador2 = 3,
	Potenciador3 = 3,
	Potenciador4 = 3,
	Potenciador5 = 3,
	Potenciador6 = 3,
	Potenciador7 = 3,
	Potenciador8 = 3,
	Potenciador9 = 3,
	Potenciador10 = 3,
	Potenciador11 = 3,
	Potenciador12 = 3,
	Potenciador13 = 3,
	Potenciador14 = 3,
	Potenciador15 = 3,
	Potenciador16 = 3,
	Potenciador17 = 3,
	Potenciador18 = 3,
	Potenciador19 = 3,
	Potenciador20 = 3,
	Potenciador21 = 3,
	Potenciador22 = 3,
	Potenciador23 = 3,
	Potenciador24 = 3,
	Chest = 5,
	Chest2 = 5,
	Chest3 = 5,
	Soul = 10,
	Soul2 = 10,
	Soul3 = 10,
	Coin = 50,
	Coin2 = 50,
	Coin3 = 50,
	PropTapiz = 20,
	Stone1 = 50,
	Stone2 = 50,
	-- Cobweb1 = 10,
	-- Cobweb2 = 10,
	-- Cobweb3 = 10,
	-- Cobweb4 = 10,
	-- Cobweb5 = 10,
	AltarSacrificio = 1,
	MovableText = 10,
	MovableTextDamage = 20,
	triggerTutorial1 = 1,
	triggerTutorial2 = 1,
	triggerTutorial3 = 1,
	triggerTutorial4 = 1,
	triggerTutorial5 = 1,
	triggerTutorial6 = 1,
	triggerTutorial7 = 1,
	triggerTutorial8 = 1,
	triggerTutorial9 = 1,
	triggerTutorial10 = 1,
	triggerTutorial11 = 1,
	triggerTutorial12 = 1,
	triggerTutorial13 = 1,
	triggerTutorial14 = 1,
	triggerTutorial15 = 1,

	SpiderDodge = 10,
	SpiderKami = 10,
	Wompy  = 10,
	SkullShoot = 10,
	SkullSummon = 10,
	Chulu = 10,
	MinionSummonUniDir = 10,
	--EnemAppr = 10,
	--EnemPong = 10,
	--EnemApprShootPl = 10,
	--EnemShootRay = 10,
	--EnemPongShootPl =10,
	--EnemShootUni = 10,
	--EnemApprWander = 10,
	--EnemApprMDShootRay = 10,
	--EnemApprKami = 10,
	--EnemApprMDKami = 10,
	--EnemApprDodge = 10,
	--EnemApprMDDodge = 10,
	--EnemApprDefend = 10,
	--EnemApprMDDefend = 10,
	--EnemApprMDStealLife = 10,
	LaserBeam = 20,
	LaserBall = 10,
	ShieldSpecial = 2,
	SpecialBullet = 10,
	NormalBullet = 100,
	EnemyBullet = 100,
	TongueBall = 5,
	BulletDart = 20,
	BulletDartCanibal = 10,
	BulletDartCanibalSpecial = 10,
	GreenSwordSlash = 5,
	GreenSwordSlash2 = 5,
	GreenSwordSlash3 = 5,
	GreenSwordSlash4 = 5,
	GreenSwordSlash5 = 5,
	JumpRight = 10,
	JumpLeft = 10,

	UsableObjectSalto = 2,
	UsableObjectBarraVidaEnemigo = 3,
	UsableObjectRegeneracion = 3,
	UsableObjectAumentoVidaMaxima = 3,
	UsableObjectAumentoVidaMaxima = 3,
	UsableObjectAumentoPorcentajeAlmas = 3,
	UsableObjectDamageMeleeEnemy = 3,

	UsableObjectBroadSword = 3,
	UsableObjectGreenSword = 3,
	UsableObjectDartGun = 3,
	UsableObjectLaser = 3,
	UsableObjectKatana = 3,
	UsableObjectShield = 3,
	UsableObjectTongue = 3,

	AlmaAzulFeedback = 10,
	AlmaVerdeFeedback = 10,
	AlmaRojaFeedback = 10,
	AltarFeedback = 2,
	LaserBeamParticle = 20,
	HumoMuerteEnemigo = 40,
	HumoVioleta = 5,
	HumoSangre = 3,
	ParticulaAmbientacion = 10,
	ExplosionPuerta = 1,
	ExplosionLaser = 5,
	ExplosionAranha = 3,
	Heiser = 10,
	HumoVenenoso = 10,
	TrampaRayo = 10,
	ParticulaPuertaCerrada = 1,
	ParticulaPuertaCerradaAbajo = 1,
	ParticulaPuertaAbierta = 1,
	ParticulaChupaAlmas = 10,
	Chispa = 10,
	ChispaDanhoPlayer = 10,
	ChispaDanhoEnemy = 10,
	SpawnEnem = 50,
	puntoTutorial = 20,

	TILE_FRAGILE = 20,
	TILE_TRAMPILLA = 5,
	TILE_FRAGILE_BORDE = 20,
	TILE_STONES = 20,
	TILE_PLATFORM = 20,

	cajaEntera = 3,
	cajaParte1 = 15,
	cajaParte2 = 15,
	cajaParte3 = 15,
	cajaParte4 = 15,
	cajaParte5 = 15,
	barrilEntero = 3,
	barrilParte1 = 15,
	barrilParte2 = 15,
	barrilParte3 = 15,
	barrilParte4 = 15,
	barrilParte5 = 15,
	calavera = 3,
	pilaCalaveras = 3,
	calaveraParte1 = 15,
	calaveraParte2 = 15,
	calaveraParte3 = 15,
}

FuncionesRellenadoPoolInicial = 
{
}


function FuncionesRellenadoPoolInicial.createEntities()

	-- Creamos el mapa dummy
	local mapaLogico = createLogicMap("mapaDummy")

	-- --Creamos las entidades

	for key, value in pairs(entidadesIniciales) do
		local cantidad = value
		while cantidad > 0 do
			entityfactory:createEntityByType(key, Vector3(0,0,0), mapaLogico)
			--Log.Debug("Entidad numero "..cantidad..": "..key.." creada")
			cantidad = cantidad - 1
		end
	end
	
	-- --Destruir mapa
	deleteLogicMap(mapaLogico)
end